=== cjbrooks12/arkham-explorer/app/src/jsMain/resources/ArkhamHorrorLCG/encounter-sets/$schema.json
{
    "$schema": "https://json-schema.org/draft/2019-09/schema",
    "type": "object",
    "properties": {
        "name": {
            "type": "string"
        },
        "id": {
            "type": "string"
        },
        "icon": {
            "type": "string",
            "format": "uri"
        },
        "arkhamDbEntry": {
            "type": "string",
            "format": "uri"
        },
        "releaseDate": {
            "type": "string",
            "format": "date"
        },
        "returnTo": {
            "type": "boolean"
        },
        "scenarios": {
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "name": {
                        "type": "string"
                    },
                    "id": {
                        "type": "string"
                    },
                    "icon": {
                        "type": "string",
                        "format": "uri"
                    },
                    "arkhamDbEntry": {
                        "type": "string",
                        "format": "uri"
                    },
                    "encounterSets": {
                        "type": "array",
                        "items": {
                            "type": "object",
                            "uniqueItems": true,
                            "properties": {
                                "name": {
                                    "type": "string"
                                },
                                "conditional": {
                                    "type": "boolean"
                                },
                                "setAside": {
                                    "type": "boolean"
                                }
                            },
                            "required": [
                                "name",
                                "conditional",
                                "setAside"
                            ],
                            "additionalProperties": false
                        }
                    }
                },
                "required": [
                    "name",
                    "icon",
                    "encounterSets"
                ],
                "additionalProperties": false
            }
        },
        "encounterSets": {
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "name": {
                        "type": "string"
                    },
                    "icon": {
                        "type": "string",
                        "format": "uri"
                    },
                    "arkhamDbEntry": {
                        "type": "string",
                        "format": "uri"
                    }
                },
                "required": [
                    "name",
                    "icon"
                ],
                "additionalProperties": false
            }
        },
        "investigators": {
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "name": {
                        "type": "string"
                    },
                    "mainClass": {
                        "type": "string",
                        "enum": ["Guardian", "Rogue", "Seeker", "Survivor", "Mystic", "Neutral"]
                    },
                    "arkhamDbEntry": {
                        "type": "string",
                        "format": "uri"
                    }
                },
                "required": [
                    "name",
                    "mainClass",
                    "arkhamDbEntry"
                ],
                "additionalProperties": false
            }
        }
    },
    "required": [
        "name",
        "id",
        "icon",
        "arkhamDbEntry",
        "releaseDate",
        "returnTo",
        "scenarios",
        "encounterSets",
        "investigators"
    ],
    "additionalProperties": false
}

=== cjbrooks12/arkham-explorer/app/src/jsMain/resources/ArkhamHorrorLCG/encounter-sets/night-of-the-zealot.json
{
    "name": "Night of the Zealot",
    "id": "1",
    "icon": "https://cf.geekdo-images.com/original/img/JyAKQ5RxTet7xpBoRd8N2cVPYqM=/0x0/pic3503052.png",
    "arkhamDbEntry": "https://arkhamdb.com/set/core",
    "releaseDate": "2016-11-10",
    "returnTo": false,
    "scenarios": [
        {
            "name": "The Gathering",
            "id": "1-1",
            "icon": "https://cf.geekdo-images.com/original/img/S7eCJwohbbghDADgY7xEp4fB9VY=/0x0/pic3503053.png",
            "encounterSets": [
                { "name": "The Gathering", "conditional": false, "setAside": false },
                { "name": "Rats",          "conditional": false, "setAside": false },
                { "name": "Ghouls",        "conditional": false, "setAside": false },
                { "name": "Striking Fear", "conditional": false, "setAside": false },
                { "name": "Ancient Evils", "conditional": false, "setAside": false },
                { "name": "Chilling Cold", "conditional": false, "setAside": false }
            ]
        },
        {
            "name": "The Midnight Masks",
            "id": "1-2",
            "icon": "https://cf.geekdo-images.com/original/img/h0XcCJQpTEgW4XxetASpjLzcR9A=/0x0/pic3503054.png",
            "encounterSets": [
                { "name": "The Midnight Masks", "conditional": false, "setAside": false },
                { "name": "Chilling Cold",      "conditional": false, "setAside": false },
                { "name": "Dark Cult",          "conditional": false, "setAside": false },
                { "name": "Nightgaunts",        "conditional": false, "setAside": false },
                { "name": "Locked Doors",       "conditional": false, "setAside": false },
                { "name": "Cult of Umôrdhoth",  "conditional": false, "setAside": true  }
            ]
        },
        {
            "name": "The Devourer Below",
            "id": "1-3",
            "icon": "https://cf.geekdo-images.com/original/img/qFXZpOLtp7sntHY-FQIK8nZgMdo=/0x0/pic3503056.png",
            "encounterSets": [
                { "name": "The Devourer Below",       "conditional": false, "setAside": false },
                { "name": "Ghouls",                   "conditional": false, "setAside": false },
                { "name": "Striking Fear",            "conditional": false, "setAside": false },
                { "name": "Ancient Evils",            "conditional": false, "setAside": false },
                { "name": "Dark Cult",                "conditional": false, "setAside": false },
                { "name": "Agents of Hastur",         "conditional": true,  "setAside": false  },
                { "name": "Agents of Yog-Sothoth",    "conditional": true,  "setAside": false  },
                { "name": "Agents of Shub Niggurath", "conditional": true,  "setAside": false  },
                { "name": "Agenths of Cthulhu",       "conditional": true,  "setAside": false  }
            ]
        }
    ],
    "encounterSets": [
        {
            "name": "The Gathering",
            "icon": "https://cf.geekdo-images.com/original/img/S7eCJwohbbghDADgY7xEp4fB9VY=/0x0/pic3503053.png",
            "arkhamDbEntry": "https://arkhamdb.com/find?q=m:torch"
        },
        {
            "name": "The Midnight Masks",
            "icon": "https://cf.geekdo-images.com/original/img/h0XcCJQpTEgW4XxetASpjLzcR9A=/0x0/pic3503054.png",
            "arkhamDbEntry": "https://arkhamdb.com/find?q=m:arkham"
        },
        {
            "name": "The Devourer Below",
            "icon": "https://cf.geekdo-images.com/original/img/qFXZpOLtp7sntHY-FQIK8nZgMdo=/0x0/pic3503056.png",
            "arkhamDbEntry": "https://arkhamdb.com/find?q=m:tentacles"
        },
        {
            "name": "Cult of Umôrdhoth",
            "icon": "https://cf.geekdo-images.com/original/img/EJ3nMieXgX6mac0e2gmJ5e5_EGQ=/0x0/pic3503055.png",
            "arkhamDbEntry": "https://arkhamdb.com/find?q=m:cultists"
        },
        {
            "name": "Rats",
            "icon": "https://cf.geekdo-images.com/original/img/IOV2zK1AyoMatAVZCkV6FnVGhHI=/0x0/pic3503057.png",
            "arkhamDbEntry": "https://arkhamdb.com/find?q=m:rats"
        },
        {
            "name": "Ghouls",
            "icon": "https://cf.geekdo-images.com/original/img/r8TvQfIdLrv_oJs01keCRhy0a4k=/0x0/pic3503058.png",
            "arkhamDbEntry": "https://arkhamdb.com/find?q=m:ghouls"
        },
        {
            "name": "Striking Fear",
            "icon": "https://cf.geekdo-images.com/original/img/IjvxebRfBLUOLgp5FCehn-yaDNI=/0x0/pic3503059.png",
            "arkhamDbEntry": "https://arkhamdb.com/find?q=m:striking_fear"
        },
        {
            "name": "Ancient Evils",
            "icon": "https://cf.geekdo-images.com/original/img/tr1MnYB7Mn1hg67vj8qR-Y3IfOY=/0x0/pic3503060.png",
            "arkhamDbEntry": "https://arkhamdb.com/find?q=m:ancient_evils"
        },
        {
            "name": "Chilling Cold",
            "icon": "https://cf.geekdo-images.com/original/img/F2hVLsiWE3SU4lOMFBat0Pdm5cw=/0x0/pic3503061.png",
            "arkhamDbEntry": "https://arkhamdb.com/find?q=m:chilling_cold"
        },
        {
            "name": "Dark Cult",
            "icon": "https://cf.geekdo-images.com/original/img/yxfb_pYx5nE21jpIDrZYbH_oowA=/0x0/pic3503062.png",
            "arkhamDbEntry": "https://arkhamdb.com/find?q=m:pentagram"
        },
        {
            "name": "Nightgaunts",
            "icon": "https://cf.geekdo-images.com/original/img/qKmpsv1-y0MX0nZ_MLNvYPlJuK4=/0x0/pic3503063.png",
            "arkhamDbEntry": "https://arkhamdb.com/find?q=m:nightgaunts"
        },
        {
            "name": "Locked Doors",
            "icon": "https://cf.geekdo-images.com/original/img/Yx73-MvMIFh8ARI-SJ1m80oMfAg=/0x0/pic3503064.png",
            "arkhamDbEntry": "https://arkhamdb.com/find?q=m:locked_doors"
        },
        {
            "name": "Agents of Hastur",
            "icon": "https://cf.geekdo-images.com/original/img/FFp7lhe66LMTX3DS4OAWzgQxj1Q=/0x0/pic3503065.png",
            "arkhamDbEntry": "https://arkhamdb.com/find?q=m:agents_of_hastur"
        },
        {
            "name": "Agents of Yog-Sothoth",
            "icon": "https://cf.geekdo-images.com/original/img/zAaCKQJzDbm6Y1TfVlvLGjYI29E=/0x0/pic3503066.png",
            "arkhamDbEntry": "https://arkhamdb.com/find?q=m:agents_of_yog"
        },
        {
            "name": "Agents of Shub Niggurath",
            "icon": "https://cf.geekdo-images.com/original/img/RxELtyAqIZX5huwUrlfiC95Onuk=/0x0/pic3503067.png",
            "arkhamDbEntry": "https://arkhamdb.com/find?q=m:agents_of_shub"
        },
        {
            "name": "Agenths of Cthulhu",
            "icon": "https://cf.geekdo-images.com/original/img/ecRtSQBkwnnG8SHRVU0gYYetcu0=/0x0/pic3503068.png",
            "arkhamDbEntry": "https://arkhamdb.com/find?q=m:agents_of_cthulhu"
        }
    ],
    "investigators": [
        {
            "name": "Roland Banks",
            "mainClass": "Guardian",
            "arkhamDbEntry": "https://arkhamdb.com/card/01001"
        },
        {
            "name": "Daisy Walker",
            "mainClass": "Seeker",
            "arkhamDbEntry": "https://arkhamdb.com/card/01002"
        },
        {
            "name": "\"Skids\" O-Toole",
            "mainClass": "Rogue",
            "arkhamDbEntry": "https://arkhamdb.com/card/01003"
        },
        {
            "name": "Agnes Baker",
            "mainClass": "Mystic",
            "arkhamDbEntry": "https://arkhamdb.com/card/01004"
        },
        {
            "name": "Wendy Adams",
            "mainClass": "Survivor",
            "arkhamDbEntry": "https://arkhamdb.com/card/01005"
        }
    ]
}

=== cjbrooks12/arkham-explorer/app/src/jsMain/resources/ArkhamHorrorLCG/encounter-sets/the-dunwich-legacy-return-to.json
{
    "name": "Return To The Dunwich Legacy",
    "id": "2r",
    "icon": "https://cf.geekdo-images.com/original/img/9AsAgcuMCQ_7tWTCN7KAWJGZe48=/0x0/pic4773025.png",
    "arkhamDbEntry": "",
    "returnTo": true,
    "releaseDate": "2019-01-10",
    "scenarios": [
        {
            "name": "Return To Extracurricular Activity",
            "icon": "https://cf.geekdo-images.com/original/img/Ke8kelsoQcdg2N0fURh_RCqJg_k=/0x0/pic4773026.png",
            "encounterSets": [
                { "name": "Return To Extracurricular Activity", "conditional": false, "setAside": false },
                { "name": "Sorcery",                            "conditional": false, "setAside": false },
                { "name": "Bishop's Thralls",                   "conditional": false, "setAside": false },
                { "name": "Whippoorwills",                      "conditional": false, "setAside": false },
                { "name": "Beyond the Threshold",               "conditional": false, "setAside": false },
                { "name": "Resurgent Evils",                    "conditional": false, "setAside": false },
                { "name": "Secret Doors",                       "conditional": false, "setAside": false },
                { "name": "Yog-Sothoth's Emissaries",           "conditional": false, "setAside": false }
            ]
        },
        {
            "name": "Return To The House Always Wins",
            "icon": "https://cf.geekdo-images.com/original/img/qU5aUipSYk6n1jkW3L6wHrFtyo4=/0x0/pic4773027.png",
            "encounterSets":  [
                { "name": "Return To The House Always Wins", "conditional": false, "setAside": false },
                { "name": "Rats",                            "conditional": false, "setAside": false },
                { "name": "Bad Luck",                        "conditional": false, "setAside": false },
                { "name": "Naomi's Crew",                    "conditional": false, "setAside": false },
                { "name": "Hideous Abominations",            "conditional": false, "setAside": true  },
                { "name": "Erratic Fear",                    "conditional": false, "setAside": true  }
            ]
        },
        {
            "name": "Return To The Miskatonic Museum",
            "icon": "https://cf.geekdo-images.com/original/img/ayZAjbkKcpWN_g42H1Hx45kP33c=/0x0/pic4773028.png",
            "encounterSets":  [
                { "name": "Return To The Miskatonic Museum", "conditional": false, "setAside": false },
                { "name": "Sorcery",                         "conditional": false, "setAside": false },
                { "name": "Bad Luck",                        "conditional": false, "setAside": false },
                { "name": "Beyond the Threshold",            "conditional": false, "setAside": false },
                { "name": "Creeping Cold",                   "conditional": false, "setAside": false },
                { "name": "Secret Doors",                    "conditional": false, "setAside": false }
            ]
        },
        {
            "name": "Return To The Essex County Express",
            "icon": "https://cf.geekdo-images.com/original/img/YME06jTGPq2x9tWDSDgUFHEag68=/0x0/pic4773029.png",
            "encounterSets":  [
                { "name": "Return To The Essex County Express", "conditional": false, "setAside": false },
                { "name": "Dark Cult",                          "conditional": false, "setAside": false },
                { "name": "Beyond the Threshold",               "conditional": false, "setAside": false },
                { "name": "Resurgent Evils",                    "conditional": false, "setAside": false },
                { "name": "Erratic Fear",                       "conditional": false, "setAside": false }
            ]
        },
        {
            "name": "Return To Blood on the Altar",
            "icon": "https://cf.geekdo-images.com/original/img/eSJ8TNE7-wIcjp_jmbhMMW4B46o=/0x0/pic4773030.png",
            "encounterSets":  [
                { "name": "Return To Blood on the Altar", "conditional": false, "setAside": false },
                { "name": "Nightgaunts",                  "conditional": false, "setAside": false },
                { "name": "Dunwich",                      "conditional": false, "setAside": false },
                { "name": "Whippoorwills",                "conditional": false, "setAside": false },
                { "name": "Naomi's Crew",                 "conditional": false, "setAside": true  },
                { "name": "Resurgent Evils",              "conditional": false, "setAside": false }
            ]
        },
        {
            "name": "Return To Undimensioned and Unseen",
            "icon": "https://cf.geekdo-images.com/original/img/e5YafDgERaMsIjL02UZtsNeYAB4=/0x0/pic4773031.png",
            "encounterSets":  [
                { "name": "Return To Undimensioned and Unseen", "conditional": false, "setAside": false },
                { "name": "Dunwich",                            "conditional": false, "setAside": false },
                { "name": "Whippoorwills",                      "conditional": false, "setAside": false },
                { "name": "Beast Thralls",                      "conditional": false, "setAside": false },
                { "name": "Erratic Fear",                       "conditional": false, "setAside": false }
            ]
        },
        {
            "name": "Return To Where Doom Awaits",
            "icon": "https://cf.geekdo-images.com/original/img/gf_RXUhbEdav8Z7-ad_nktwKHwc=/0x0/pic4773032.png",
            "encounterSets":  [
                { "name": "Return To Where Doom Awaits", "conditional": false, "setAside": false },
                { "name": "Sorcery",                     "conditional": false, "setAside": false },
                { "name": "Bishop's Thralls",            "conditional": false, "setAside": false },
                { "name": "Beast Thralls",               "conditional": false, "setAside": false },
                { "name": "Hideous Abominations",        "conditional": false, "setAside": true  },
                { "name": "Resurgent Evils",             "conditional": false, "setAside": false },
                { "name": "Erratic Fear",                "conditional": false, "setAside": false },
                { "name": "Creeping Cold",               "conditional": false, "setAside": false }
            ]
        },
        {
            "name": "Return To Lost in Time and Space",
            "icon": "https://cf.geekdo-images.com/original/img/LexBV0cK3gcTDql1XxGBFpoLLDU=/0x0/pic4773033.png",
            "encounterSets":  [
                { "name": "Return To Lost in Time and Space", "conditional": false, "setAside": false },
                { "name": "Sorcery",                          "conditional": false, "setAside": false },
                { "name": "Beyond the Threshold",             "conditional": false, "setAside": false },
                { "name": "Hideous Abominations",             "conditional": false, "setAside": false },
                { "name": "Yog-Sothoth's Emissaries",         "conditional": false, "setAside": false }
            ]
        }
    ],
    "encounterSets": [
        {
            "name": "Return To Extracurricular Activity",
            "icon": "https://cf.geekdo-images.com/original/img/Ke8kelsoQcdg2N0fURh_RCqJg_k=/0x0/pic4773026.png"
        },
        {
            "name": "Return To the House Always Wins",
            "icon": "https://cf.geekdo-images.com/original/img/qU5aUipSYk6n1jkW3L6wHrFtyo4=/0x0/pic4773027.png"
        },
        {
            "name": "Return To The Miskatonic Museum",
            "icon": "https://cf.geekdo-images.com/original/img/ayZAjbkKcpWN_g42H1Hx45kP33c=/0x0/pic4773028.png"
        },
        {
            "name": "Return To The Essex County Express",
            "icon": "https://cf.geekdo-images.com/original/img/YME06jTGPq2x9tWDSDgUFHEag68=/0x0/pic4773029.png"
        },
        {
            "name": "Return To Blood on the Altar",
            "icon": "https://cf.geekdo-images.com/original/img/eSJ8TNE7-wIcjp_jmbhMMW4B46o=/0x0/pic4773030.png"
        },
        {
            "name": "Return To Undimensioned and Unseen",
            "icon": "https://cf.geekdo-images.com/original/img/e5YafDgERaMsIjL02UZtsNeYAB4=/0x0/pic4773031.png"
        },
        {
            "name": "Return To Where Doom Awaits",
            "icon": "https://cf.geekdo-images.com/original/img/gf_RXUhbEdav8Z7-ad_nktwKHwc=/0x0/pic4773032.png"
        },
        {
            "name": "Return To Lost in Time and Space",
            "icon": "https://cf.geekdo-images.com/original/img/LexBV0cK3gcTDql1XxGBFpoLLDU=/0x0/pic4773033.png"
        },
        {
            "name": "Beyond the Threshold",
            "icon": "https://cf.geekdo-images.com/original/img/JYkQtmXmiydTZ0AddQTroWyHL0s=/0x0/pic4773034.png"
        },
        {
            "name": "Resurgent Evils",
            "icon": "https://cf.geekdo-images.com/original/img/fP7gnYdA94k8ziYIeIm5hqoV3LA=/0x0/pic4773035.png"
        },
        {
            "name": "Erratic Fear",
            "icon": "https://cf.geekdo-images.com/original/img/V3j9tnPY_uVDwIVa-S9Ckp423O8=/0x0/pic4773038.png"
        },
        {
            "name": "Creeping Cold",
            "icon": "https://cf.geekdo-images.com/original/img/tbn2Tig2KjsAdyVuXgeho5tyjlE=/0x0/pic4773037.png"
        },
        {
            "name": "Secret Doors",
            "icon": "https://cf.geekdo-images.com/original/img/qnLbekTh_J6hwTPBwguc5DXARaE=/0x0/pic4773036.png"
        },
        {
            "name": "Yog-Sothoth's Emissaries",
            "icon": "https://cf.geekdo-images.com/original/img/N1hgQs7FIipoogiX9eLIMZvMTIs=/0x0/pic4773039.png"
        }
    ],
    "investigators": []
}
